import { sql } from "drizzle-orm";
import { boolean, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import type { GenerationLogEntry, GenerationStage, GenerationStatus, StoredAppSpec } from "@buildflow/contracts";
export const generationStatus = pgEnum("generation_status", ["idle", "queued", "running", "completed", "failed"] as const satisfies readonly GenerationStatus[]);
export const generationStage = pgEnum("generation_stage", ["analysis", "planning", "generation", "validation"] as const satisfies readonly GenerationStage[]);
export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: varchar("email", { length: 255 }).notNull(), passwordHash: text("password_hash").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("users_email_unique").on(table.email)]);
export const projects = pgTable("projects", { id: uuid("id").defaultRandom().primaryKey(), ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), prompt: text("prompt").notNull(), currentVersionId: uuid("current_version_id"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
// Retained only for locally created legacy demo projects. New generated applications use projectPreviewStates.
export const projectTasks = pgTable("project_tasks", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), title: varchar("title", { length: 180 }).notNull(), completed: boolean("completed").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const generationJobs = pgTable("generation_jobs", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), status: generationStatus("status").default("queued").notNull(), stage: generationStage("stage"), logs: jsonb("logs").$type<GenerationLogEntry[]>().default([]).notNull(), failureReason: text("failure_reason"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => [uniqueIndex("generation_jobs_one_active_project").on(table.projectId).where(sql`${table.status} in ('queued', 'running')`)]);
export const projectVersions = pgTable("project_versions", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), sequence: varchar("sequence", { length: 16 }).notNull(), appSpec: jsonb("app_spec").$type<StoredAppSpec>().notNull(), summary: text("summary").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const projectPreviewStates = pgTable("project_preview_states", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), versionId: uuid("version_id").notNull().references(() => projectVersions.id, { onDelete: "cascade" }), state: jsonb("state").$type<Record<string, unknown>>().default({}).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("project_preview_states_project_version_unique").on(table.projectId, table.versionId)]);
export const generatedFiles = pgTable("generated_files", { id: uuid("id").defaultRandom().primaryKey(), versionId: uuid("version_id").notNull().references(() => projectVersions.id, { onDelete: "cascade" }), path: varchar("path", { length: 255 }).notNull(), language: varchar("language", { length: 16 }).notNull(), contents: text("contents").notNull() });
